use super::*;

#[test]
pub fn config_toml() {
    // Arrange
    let project = CargoWorkspace::new()
        .bin_package(
            ".",
            r#"
[package]
name = "test-dummy"
version = "0.1.0"
edition = "2018"

[dependencies]
"#,
        )
        .touch(".cargo/config.toml")
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    assert_eq!(1, skeleton.manifests.len());
    let manifest = &skeleton.manifests[0];
    assert_eq!(Path::new("Cargo.toml"), manifest.relative_path);
    cook_directory
        .child("src")
        .child("main.rs")
        .assert("fn main() {}");
    cook_directory
        .child(".cargo")
        .child("config.toml")
        .assert(predicate::path::exists());
}

#[test]
pub fn version() {
    // Arrange
    let project = CargoWorkspace::new()
        .bin_package(
            ".",
            r#"
[package]
name = "test-dummy"
version = "1.2.3"
edition = "2018"

[dependencies]
"#,
        )
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    assert_eq!(1, skeleton.manifests.len());
    let manifest = skeleton.manifests[0].clone();
    assert!(manifest.contents.contains(r#"version = "0.0.1""#));
    assert!(!manifest.contents.contains(r#"version = "1.2.3""#));
}

#[test]
pub fn version_lock() {
    // Arrange
    let project = CargoWorkspace::new()
        .bin_package(
            ".",
            r#"
[package]
name = "test-dummy"
version = "1.2.3"
edition = "2018"

[dependencies]        
"#,
        )
        .file(
            "Cargo.lock",
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "test-dummy"
version = "1.2.3"
    "#,
        )
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    let lock_file = skeleton.lock_file.expect("there should be a lock_file");
    assert!(!lock_file.contains(
        r#"
[[package]]
name = "test-dummy"
version = "1.2.3"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "test-dummy"
version = "0.0.1"
"#
    ));
}

#[test]
pub fn workspace_version_lock() {
    // Arrange
    // project-a is named with a dash to test that such unnormalized name can be handled.
    let project = CargoWorkspace::new()
        .manifest(
            ".",
            r#"
[workspace]
members = [
    "src/project-a",
    "src/project_b",
]
"#,
        )
        .bin_package(
            "src/project-a",
            r#"
[package]
name = "project-a"
version = "1.2.3"
edition = "2018"

[[bin]]
name = "test-dummy"
path = "src/main.rs"

[dependencies]
either = { version = "=1.8.1" }        
"#,
        )
        .lib_package(
            "src/project_b",
            r#"
[package]
name = "project_b"
version = "4.5.6"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
either = { version = "=1.8.1" }
project-a = { version = "1.2.3", path = "../project-a" }   
"#,
        )
        .file(
            "Cargo.lock",
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "either"
version = "1.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7fcaabb2fef8c910e7f4c7ce9f67a1283a1715879a7c230ca9d6d1ae31f16d91"

[[package]]
name = "project-a"
version = "1.2.3"
dependencies = [
 "either",
]

[[package]]
name = "project_b"
version = "4.5.6"
dependencies = [
 "either",
 "project_a",
]
"#,
        )
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    let lock_file = skeleton.lock_file.expect("there should be a lock_file");
    assert!(!lock_file.contains(
        r#"
[[package]]
name = "project-a"
version = "1.2.3"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "project-a"
version = "0.0.1"
"#
    ));
    assert!(!lock_file.contains(
        r#"
[[package]]
name = "project_b"
version = "4.5.6"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "project_b"
version = "0.0.1"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "either"
version = "1.8.1"
"#
    ));

    let first = skeleton.manifests[0].clone();
    check(
        &first.contents,
        expect_test::expect![[r#"
        [workspace]
        members = ["src/project-a", "src/project_b"]
    "#]],
    );
    let second = skeleton.manifests[1].clone();
    check(
        &second.contents,
        expect_test::expect![[r#"
            [[bin]]
            path = "src/main.rs"
            name = "test-dummy"
            plugin = false
            proc-macro = false
            edition = "2018"
            required-features = []

            [package]
            name = "project-a"
            edition = "2018"
            version = "0.0.1"

            [dependencies.either]
            version = "=1.8.1"
        "#]],
    );
    let third = skeleton.manifests[2].clone();
    check(
        &third.contents,
        expect_test::expect![[r#"
            [package]
            name = "project_b"
            edition = "2018"
            version = "0.0.1"

            [dependencies.either]
            version = "=1.8.1"

            [dependencies.project-a]
            version = "0.0.1"
            path = "../project-a"

            [lib]
            path = "src/lib.rs"
            name = "project_b"
            plugin = false
            proc-macro = false
            edition = "2018"
            required-features = []
            crate-type = ["cdylib"]
        "#]],
    );
}

#[test]
pub fn transitive_workspace_dependency_not_masked() {
    // Arrange
    let project = CargoWorkspace::new()
        .manifest(
            ".",
            r#"
[workspace]
members = [
    "src/project_a",
    "src/project_b",
]
"#,
        )
        .bin_package(
            "src/project_a",
            r#"
[package]
name = "project_a"
version = "2.2.2"
edition = "2018"

[[bin]]
name = "test-dummy"
path = "src/main.rs"

[dependencies]
either = { version = "=1.8.1" }
"#,
        )
        .lib_package(
            "src/project_b",
            r#"
[package]
name = "project_b"
version = "5.5.5"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
"#,
        )
        .file(
            "Cargo.lock",
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "either"
version = "1.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7fcaabb2fef8c910e7f4c7ce9f67a1283a1715879a7c230ca9d6d1ae31f16d91"
dependencies = [
 "project_b 5.5.5 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "project_a"
version = "2.2.2"
dependencies = [
 "either",
]

[[package]]
name = "project_b"
version = "5.5.5"

[[package]]
name = "project_b"
version = "5.5.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7fcaabb2fef8c910e7f4c7ce9f67a1283a1715879a7c230ca9d6d1ae31f16d91"
"#,
        )
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    let lock_file = skeleton.lock_file.expect("there should be a lock_file");
    assert!(!lock_file.contains(
        r#"
[[package]]
name = "project_a"
version = "2.2.2"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "project_a"
version = "0.0.1"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "project_b"
version = "5.5.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7fcaabb2fef8c910e7f4c7ce9f67a1283a1715879a7c230ca9d6d1ae31f16d91"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "project_b"
version = "0.0.1"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "either"
version = "1.8.1"
"#
    ));

    let first = skeleton.manifests[0].clone();
    check(
        &first.contents,
        expect_test::expect![[r#"
        [workspace]
        members = ["src/project_a", "src/project_b"]
    "#]],
    );
    let second = skeleton.manifests[1].clone();
    check(
        &second.contents,
        expect_test::expect![[r#"
            [[bin]]
            path = "src/main.rs"
            name = "test-dummy"
            plugin = false
            proc-macro = false
            edition = "2018"
            required-features = []

            [package]
            name = "project_a"
            edition = "2018"
            version = "0.0.1"

            [dependencies.either]
            version = "=1.8.1"
        "#]],
    );
    let third = skeleton.manifests[2].clone();
    check(
        &third.contents,
        expect_test::expect![[r#"
            [package]
            name = "project_b"
            edition = "2018"
            version = "0.0.1"

            [dependencies]

            [lib]
            path = "src/lib.rs"
            name = "project_b"
            plugin = false
            proc-macro = false
            edition = "2018"
            required-features = []
            crate-type = ["cdylib"]
        "#]],
    );
}

#[test]
pub fn non_local_dependency_not_masked() {
    // Arrange
    let project = CargoWorkspace::new()
        .manifest(
            ".",
            r#"
[workspace]
members = [
    "binary",
    "without",
]
"#,
        )
        .bin_package(
            "binary",
            r#"
[package]
name = "binary"
version = "2.2.2"
edition = "2021"

[dependencies]
without = "=0.1.0"
without-local = { package = "without", path = "../without", version = "=0.1.0" }

"#,
        )
        .lib_package(
            "without",
            r#"
[package]
name = "without"
version = "0.1.0"
edition = "2021"

[dependencies]

"#,
        )
        .file(
            "Cargo.lock",
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "binary"
version = "2.2.2"
dependencies = [
 "without 0.1.0",
 "without 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "without"
version = "0.1.0"

[[package]]
name = "without"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3df10e9ed85b51fa3434bc5676eaa90479ce14ac3e101c8ce07e1bb5ef0b7255"

"#,
        )
        .build();

    // Act
    let skeleton = Skeleton::derive(project.path(), None).unwrap();
    let cook_directory = TempDir::new().unwrap();
    skeleton
        .build_minimum_project(cook_directory.path(), false)
        .unwrap();

    // Assert
    let lock_file = skeleton.lock_file.expect("there should be a lock_file");
    println!("{lock_file}");
    assert!(lock_file.contains(
        r#"
[[package]]
name = "binary"
version = "0.0.1"
dependencies = ["without 0.1.0", "without 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"]

"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "without"
version = "0.0.1"
"#
    ));
    assert!(lock_file.contains(
        r#"
[[package]]
name = "without"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3df10e9ed85b51fa3434bc5676eaa90479ce14ac3e101c8ce07e1bb5ef0b7255"
"#
    ));

    let first = skeleton.manifests[0].clone();
    check(
        &first.contents,
        expect_test::expect![[r#"
        [workspace]
        members = ["binary", "without"]
    "#]],
    );
    let second = skeleton.manifests[1].clone();
    check(
        &second.contents,
        expect_test::expect![[r#"
            [[bin]]
            path = "src/main.rs"
            name = "binary"
            plugin = false
            proc-macro = false
            edition = "2021"
            required-features = []

            [package]
            name = "binary"
            edition = "2021"
            version = "0.0.1"

            [dependencies]
            without = "=0.1.0"

            [dependencies.without-local]
            version = "0.0.1"
            path = "../without"
            package = "without"
        "#]],
    );
    let third = skeleton.manifests[2].clone();
    check(
        &third.contents,
        expect_test::expect![[r#"
            [package]
            name = "without"
            edition = "2021"
            version = "0.0.1"

            [dependencies]

            [lib]
            path = "src/lib.rs"
            name = "without"
            plugin = false
            proc-macro = false
            edition = "2021"
            required-features = []
            crate-type = ["lib"]
        "#]],
    );
}
